### ISSUE TITLE
The suitable lr for mobilenet_v2 and efficientNet

### ISSUE THREAD

**Issue by detectRecog** [sony-si/ai-research#3]
Hello, thank you for your amazing work! In practice, I find that the lr for mobilenet_v1 in the demo training command is not suitable for mobilenet_v2 and efficientNet, resulting in unstable training. Could you provide your lr choices for other backbones? 

Thanks in advance.

**Comment by haihabi** [comment]
Hi, thanks for your comments.

The hyperparameters are shown in the paper https://www.ecva.net/papers/eccv_2020/papers_ECCV/html/5414_ECCV_2020_paper.php 

Is that helpful?
